var tableau= [
    {
        id :1,
       type: "appartement",
         chambres: 2,
         salon :1,
         douche : 2,
         cuisine :1,
         loyer : 130000,
         etat : "disponible",
         photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178410/imagereact/maison5_xmmkip.png",
          image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
    },
    {
        id :2,
      type: "appartement",
      chambres: 3,
      salon :2,
      douche : 2,
      cuisine :2,
      loyer : 150000,
      etat : "disponible",
      photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/appartement1_bo6pxj.png" ,
      image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
    },
    {
        id :3,
      type:"studio",
         chambres: 1,
         salon :1,
         douche :1,
         cuisine :1,
         loyer : 50000,
         etat : "disponible",
         photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178410/imagereact/studio2_ftv5ob.png",
         image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
    },
    {
         id :4,  
      type: "studio",
         chambres:2,
         salon :1,
         douche :1,
         cuisine :1,
         loyer : 55000,
         etat : "occupe",
         photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178410/imagereact/maison3_wtsbq4.png",
         image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
    },
      {
        id :5,
        type: "appartement",
           chambres:3,
           salon :2,
           douche :3,
           cuisine :1,
           loyer : 200000,
           terrase : 1,
           etat : "occupe",
           photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/studio1_ti3hkb.png",
           image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
      },
      
        {
           id :6,
          type: "studio",
             chambres:1,
             salon :1,
             douche :1,
             cuisine :1,
             loyer : 50000,
             etat : "disponible",
             photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/maison2_nuoo5o.png",
             image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
        },
          {
              id :7,
               type: "maison",
               chambres:4,
               salon :1,
               douche :2,
               cuisine :1,
               garage : 1,
               loyer : 160000,
               etat : "visitable",
               photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/maison4_zuimfg.png",
               image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
          },
            {
                 id :8,
                 type: "appartement",
                 chambres:3,
                 salon :1,
                 douche :1,
                 cuisine :1,
                 loyer : 130000,
                 etat : "occupe",
                photo: "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/maison1_uy1e2r.png",
                image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
            },
              {
                  id :9,
                   type: "studio",
                   chambres:1,
                   salon :1,
                   douche :1,
                   cuisine :1,
                   loyer : 60000,
                   etat : "visitable",
                   photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/appartement2_ax6sw5.png",
                   image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
              },
              
                {
                     id :10,
                  type:"maison",
                     chambres:4,
                     salon :2,
                     douche :2,
                     cuisine :2,
                     piscine : 1,
                     loyer : 200000,
                     etat : "occupe",
                     photo : "https://res.cloudinary.com/doratine/image/upload/w_300/v1619178409/imagereact/maison4_zuimfg.png",
                     image:"https://res.cloudinary.com/doratine/image/upload/v1619178408/imagereact/coeur3_ngqpqw.png",
                },
     
  ]
  export default tableau;